apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
    service: cart
spec:
  ports:
  - name: http-cart
    port: 8080
    targetPort: 8080
  selector:
    app: cart
    service: cart
