apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    service: mysql
spec:
  ports:
  - name: mysql-mysqldb
    port: 3306
    targetPort: 3306
  selector:
    app: mysql
    service: mysql
