apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    service: payment
spec:
  ports:
  - name: http-payment
    port: 8080
    targetPort: 8080
  selector:
    app: payment
    service: payment
