apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    service: redis
  name: redis
spec:
  ports:
  - name: redis-redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    service: redis
