apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
    service: shipping
spec:
  ports:
  - name: http-shipping
    port: 8080
    targetPort: 8080
  selector:
    app: shipping
    service: shipping
