apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    service: user
spec:
  ports:
  - name: http-user
    port: 8080
    targetPort: 8080
  selector:
    app: user
    service: user
